name: docs
channels: conda-forge,defaults
dependencies:
    # Base depends
  - python
  - pip

    # Pip-only installs
  - pip:
    - sphinx-autoapi

  - name: Install package
    shell: bash -l {0}
    run: |
      python -m pip install . --no-deps
      conda install -c conda-forge biopandas
      conda install -c conda-forge mendeleev
      conda install -c conda-forge openmm
      conda install -c conda-forge parmed
      conda config --add channels omnia --add channels conda-forge
      conda install openforcefield
      conda install openbabel -c conda-forge
      conda list


