name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - openbabel
  - mendeleev
  - biopandas
  - openmm
  - parmed
  - openforcefield
  - pytest
  - pip:
    - sphinx-autoapi


